const menu = [
  /* 베이글 */
  {
    id: 1,
    title: "플레인 크림치즈 베이글",
    category: "bagel",
    price: "5,500원",
    image: "./images/menu01.png",
    onlyNaver: false,
    desc: "근본의 근본\n 플레인 베이글 + 크림치즈",
  },
  {
    id: 2,
    title: "누텔라 카카오 초코베이글",
    category: "bagel",
    price: "5,500원",
    image: "./images/menu02.png",
    onlyNaver: false,
    desc: "믿고 먹는 누텔라\n 초코베이글 + 크림치즈 + 누텔라 + 카카오가루토핑",
  },
  {
    id: 3,
    title: "카야 그래놀라 어니언베이글",
    category: "bagel",
    price: "5,500원",
    image: "./images/menu03",
    onlyNaver: false,
    desc: "싱가폴보다 맛있는 카야\n 어니언베이글 + 크림치즈 + 카야잼 + 그래놀라",
  },
  {
    id: 4,
    title: "초코 그래놀라 블루베리베이글",
    category: "bagel",
    price: "5,500원",
    image: "./images/menu04",
    onlyNaver: false,
    desc: "잊고 싶어도 자꾸 생각나는 초베\n 블루베리 베이글 + 크림치즈 + 블루베리잼 + 초코그래놀라",
  },
  {
    id: 5,
    title: "딸기 쿠키 크랜베리베이글",
    category: "bagel",
    price: "5,500원",
    image: "./images/menu05",
    onlyNaver: false,
    desc: "돼지바의 베이글 버전?!?\n 크랜베리 베이글 + 크림치즈 + 딸기잼 + 쿠키분태",
  },
  {
    id: 6,
    title: "애플 시나몬 모짜렐라베이글",
    category: "bagel",
    price: "5,500원",
    image: "./images/menu06",
    onlyNaver: false,
    desc: "사과가 큼직해서 깜놀\n 모짜렐라 베이글 + 크림치즈 + 애플시나몬잼 + 시나몬가루",
  },
  /* 샌드위치 */
  {
    id: 7,
    title: "계란 샌드위치",
    category: "sandwich",
    price: "3,500원",
    image: "./images/menu07",
    onlyNaver: false,
    desc: "달걀과 함께라면 무엇이든 실패없죠",
  },
  {
    id: 8,
    title: "불고기 샌드위치",
    category: "sandwich",
    price: "5,500원",
    image: "./images/menu08",
    onlyNaver: false,
    desc: "한국인 취향 저격 짭쪼름한 고기",
  },
  {
    id: 9,
    title: "햄치즈 계란 샌드위치",
    category: "sandwich",
    price: "3,900원",
    image: "./images/menu09",
    onlyNaver: false,
    desc: "전 인류를 구하는 근본 조합",
  },
  {
    id: 10,
    title: "리코타치즈 샌드위치",
    category: "sandwich",
    price: "5,500원",
    image: "./images/menu10",
    onlyNaver: false,
    desc: "부드럽고 담백 촉촉",
  },
  {
    id: 11,
    title: "크래미 샌드위치",
    category: "sandwich",
    price: "6,500원",
    image: "./images/menu11",
    onlyNaver: false,
    desc: "저지방 저칼로리",
  },
  {
    id: 12,
    title: "닭가슴살 샌드위치",
    category: "sandwich",
    price: "6,500원",
    image: "./images/menu12",
    onlyNaver: false,
    desc: "근손실 무섭닭",
  },
  /* 랩 */
  {
    id: 13,
    title: "불고기 랩",
    category: "wrap",
    price: "6,500원",
    image: "./images/menu13",
    onlyNaver: false,
    desc: "엄마 손맛 불고기로 든든하게",
  },
  {
    id: 14,
    title: "닭가슴살 랩",
    category: "wrap",
    price: "6,500원",
    image: "./images/menu14",
    onlyNaver: false,
    desc: "저탄고지 담백 그 잡채",
  },
  {
    id: 15,
    title: "크래미 랩",
    category: "wrap",
    price: "6,500원",
    image: "./images/menu15",
    onlyNaver: false,
    desc: "저지방 저칼로리로 가볍게 먹는 랩",
  },
  {
    id: 16,
    title: "소시지랩",
    category: "wrap",
    price: "6,500원",
    image: "./images/menu16",
    onlyNaver: false,
    desc: "뽀득 짭짤 소시지가 취저",
  },
  {
    id: 17,
    title: "치킨 랩",
    category: "wrap",
    price: "6,500원",
    image: "./images/menu17",
    onlyNaver: true,
    desc: "바삭하게 튀킨 치킨의 건강한 맛",
  },
  {
    id: 18,
    title: "핫새우 랩",
    category: "wrap",
    price: "6,500원",
    image: "./images/menu18",
    onlyNaver: true,
    desc: "탱클한 새우가 가득 매운 야식에 제격",
  },
];

export default menu;
