// 사칙연산 퀴즈
// 30문제 중 랜덤으로 N문제 출제됨.
const mathQuiz = [
  {
    id: 1,
    question: "3 x 5 + 6",
    a: "21",
    b: "33",
    c: "정답 없음.",
    answer: "a",
  },
  {
    id: 2,
    question: "7 - 4 + 2",
    a: "3",
    b: "5",
    c: "정답 없음.",
    answer: "b",
  },
  {
    id: 3,
    question: "6 ÷ 2 + 4",
    a: "1",
    b: "7",
    c: "정답 없음.",
    answer: "b",
  },
  {
    id: 4,
    question: "8 + 3 - 2 + 2",
    a: "9",
    b: "11",
    c: "정답 없음.",
    answer: "b",
  },
  {
    id: 5,
    question: "5 x 4 - 3",
    a: "17",
    b: "20",
    c: "정답 없음.",
    answer: "a",
  },
  {
    id: 6,
    question: "9 ÷ 3 x 2",
    a: "2",
    b: "5",
    c: "정답 없음.",
    answer: "c",
  },
  {
    id: 7,
    question: "2 + 5 x 3",
    a: "17",
    b: "21",
    c: "정답 없음.",
    answer: "a",
  },
  {
    id: 8,
    question: "4 - 2 + 7",
    a: "5",
    b: "9",
    c: "정답 없음.",
    answer: "b",
  },
  {
    id: 9,
    question: "10 ÷ 2 - 3",
    a: "2",
    b: "9",
    c: "정답 없음.",
    answer: "a",
  },
  {
    id: 10,
    question: "8 x 2 ÷ 4",
    a: "4",
    b: "16",
    c: "정답 없음.",
    answer: "a",
  },
  {
    id: 11,
    question: "((((9 ÷ 3) - (4 x 1)) + (7 + (6 ÷ 2))) - 5) + 2",
    a: "7",
    b: "8",
    c: "정답 없음.",
    answer: "c",
  },
  {
    id: 12,
    question: "((((8 + 1) ÷ 2) - (5 x 1)) + (6 + (9 ÷ 3))) - 4",
    a: "4",
    b: "5",
    c: "정답 없음.",
    answer: "c",
  },
  {
    id: 13,
    question: "((((6 ÷ 2) + (7 - (3 x 1))) - (8 + (5 ÷ 1))) + 9) ÷ 3",
    a: "1",
    b: "2",
    c: "정답 없음.",
    answer: "a",
  },
  {
    id: 14,
    question: "((((7 + 1) ÷ 2) + (5 - (2 x 1))) - (6 + (9 ÷ 3))) + 4",
    a: "2",
    b: "3",
    c: "정답 없음.",
    answer: "a",
  },
  {
    id: 15,
    question: "((((9 ÷ 3) - (4 x 1)) + (8 - (5 ÷ 1))) - 6) + 8",
    a: "1",
    b: "4",
    c: "정답 없음.",
    answer: "b",
  },
  {
    id: 16,
    question: "3 x 8 + 1 - 3",
    a: "20",
    b: "22",
    c: "정답 없음.",
    answer: "b",
  },
  {
    id: 17,
    question: "10 ÷ 2 + 5 - 3",
    a: "5",
    b: "7",
    c: "정답 없음.",
    answer: "b",
  },
  {
    id: 18,
    question: "5 + 10 - 3 x 2",
    a: "4",
    b: "6",
    c: "정답 없음.",
    answer: "c",
  },
  {
    id: 19,
    question: "3 + 2 x 5 - 10",
    a: "1",
    b: "3",
    c: "정답 없음.",
    answer: "b",
  },
  {
    id: 20,
    question: "2 x 10 - 5 + 3",
    a: "16",
    b: "18",
    c: "정답 없음.",
    answer: "b",
  },
  {
    id: 21,
    question: "4 + 8 ÷ 2 - 1",
    a: "3",
    b: "7",
    c: "정답 없음.",
    answer: "b",
  },
  {
    id: 22,
    question: "1 + 1",
    a: "2",
    b: "3",
    c: "정답 없음.",
    answer: "a",
  },
  {
    id: 23,
    question: "0 - 0",
    a: "0",
    b: "1",
    c: "정답 없음.",
    answer: "a",
  },
  {
    id: 24,
    question: "3 x 0",
    a: "0",
    b: "1",
    c: "정답 없음.",
    answer: "a",
  },
  {
    id: 25,
    question: "3 ÷ 1",
    a: "2",
    b: "3",
    c: "정답 없음.",
    answer: "b",
  },
  {
    id: 26,
    question: "5 + 7",
    a: "12",
    b: "18",
    c: "정답 없음.",
    answer: "a",
  },
  {
    id: 27,
    question: "3 x 9",
    a: "12",
    b: "27",
    c: "정답 없음.",
    answer: "b",
  },
  {
    id: 28,
    question: "38 ÷ 2",
    a: "16",
    b: "19",
    c: "정답 없음.",
    answer: "b",
  },
  {
    id: 29,
    question: "0 + 0 x 1 - 3 + 3",
    a: "1",
    b: "3",
    c: "정답 없음.",
    answer: "c",
  },
  {
    id: 30,
    question: "38 x 93",
    a: "3634",
    b: "2994",
    c: "정답 없음.",
    answer: "c",
  },
];
